$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error %O %S';
$bibtex = 'bibtex %O %B';
$clean_ext = 'aux bbl blg brf idx ilg ind lof log lot out toc fls fdb_latexmk synctex.gz';
